services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: myapp
        restart: always
        working_dir: /var/www
        volumes:
            - ../:/var/www
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d
    db:
        container_name: docker-db
        image: mysql:8.0
        volumes:
            - ./storage/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3308:3306"
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        restart: always
        logging:
            driver: "none"
        ports:
            - "8025:8025"
            - "1025:1025"
    cron:
        container_name: cron
        build: ./cron
        volumes:
            - ../:/var/www
            - ./log/cron:/var/log/cron