services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php-app
        restart: always
        working_dir: /var/www
        volumes:
            - ../src:/var/www
    nginx:
        image: nginx:latest
        container_name: php-app-nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ../src:/var/www
            - ./nginx:/etc/nginx/conf.d
    db:
        container_name: php-app-db
        image: mysql:8.0
        volumes:
            - ./storage/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3308:3306"