services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: app-lesson-226
        restart: always
        working_dir: /var/www
        volumes:
            - ../src:/var/www
    nginx:
        image: nginx:latest
        container_name: app-lesson-226-nginx
        restart: always
        ports:
            - 8000:80
        volumes:
            - ../src:/var/www
            - ./nginx:/etc/nginx/conf.d